-- Generate exact nearest-neighbor results as the ground truth for Recall@K.

-- This script requires the caller to provide the following psql variables.
-- recall_query_count: number of queries used for recall calculation.
-- top_k: number of exact neighbors stored for each query.

\if :{?recall_query_count}
\else
\echo 'missing required psql variable: recall_query_count'
\quit 1
\endif

\if :{?top_k}
\else
\echo 'missing required psql variable: top_k'
\quit 1
\endif

-- Stop immediately on SQL errors to avoid leaving incomplete ground truth.
\set ON_ERROR_STOP on

-- Disable scan paths that could use an approximate index.
SET enable_indexscan = off;
SET enable_bitmapscan = off;
SET enable_seqscan = on;

-- Use a transaction so the ground truth is either fully generated or rolled back.
BEGIN;

-- Remove ground truth generated by the previous run.
TRUNCATE TABLE vector_bench.truth;

-- Generate exact Top-K results for L2 distance.
INSERT INTO vector_bench.truth (metric, query_id, item_id, rank)
SELECT
	'l2',
	query_id,
	item_id,
	rank
FROM (
	SELECT
		q.id AS query_id,
		item.id AS item_id,
		row_number() OVER (
			PARTITION BY q.id
			ORDER BY item.distance, item.id
		)::integer AS rank
	FROM vector_bench.queries AS q
	CROSS JOIN LATERAL (
		SELECT
			i.id,
			i.embedding <-> q.embedding AS distance
		FROM vector_bench.items AS i
		ORDER BY i.embedding <-> q.embedding, i.id
		LIMIT :top_k
	) AS item
	WHERE q.id <= :recall_query_count
) AS ranked
WHERE rank <= :top_k;

-- Generate exact Top-K results for inner-product distance.
INSERT INTO vector_bench.truth (metric, query_id, item_id, rank)
SELECT
	'ip',
	query_id,
	item_id,
	rank
FROM (
	SELECT
		q.id AS query_id,
		item.id AS item_id,
		row_number() OVER (
			PARTITION BY q.id
			ORDER BY item.distance, item.id
		)::integer AS rank
	FROM vector_bench.queries AS q
	CROSS JOIN LATERAL (
		SELECT
			i.id,
			i.embedding <#> q.embedding AS distance
		FROM vector_bench.items AS i
		ORDER BY i.embedding <#> q.embedding, i.id
		LIMIT :top_k
	) AS item
	WHERE q.id <= :recall_query_count
) AS ranked
WHERE rank <= :top_k;

-- Generate exact Top-K results for cosine distance.
INSERT INTO vector_bench.truth (metric, query_id, item_id, rank)
SELECT
	'cosine',
	query_id,
	item_id,
	rank
FROM (
	SELECT
		q.id AS query_id,
		item.id AS item_id,
		row_number() OVER (
			PARTITION BY q.id
			ORDER BY item.distance, item.id
		)::integer AS rank
	FROM vector_bench.queries AS q
	CROSS JOIN LATERAL (
		SELECT
			i.id,
			i.embedding <=> q.embedding AS distance
		FROM vector_bench.items AS i
		ORDER BY i.embedding <=> q.embedding, i.id
		LIMIT :top_k
	) AS item
	WHERE q.id <= :recall_query_count
) AS ranked
WHERE rank <= :top_k;

-- Commit exact results for all three metrics.
COMMIT;

-- Print the number of generated ground-truth rows for manual verification.
SELECT
	metric,
	count(*) AS result_count,
	count(DISTINCT query_id) AS query_count,
	min(rank) AS min_rank,
	max(rank) AS max_rank
FROM vector_bench.truth
GROUP BY metric
ORDER BY metric;
